### ISSUE TITLE
Offline Backup, StatefulSet Forbidden in v0.9.0-rc.6

### ISSUE THREAD

**Issue by rofra** [stashed/stash#1061] opened 2020-03-02 08:54 UTC
In version v0.9.0-rc.6, I followed the guide https://stash.run/docs/v0.9.0-rc.6/guides/v1alpha1/offline_backup/ for Offline Backup but the backup cannot succeed with a statefulset. My Stash Operator has been created with the "Helm3" Installation section.

InitContainer is correctly modified, the cronjob is set, it restarts on time but this is what I get in the Operator logs:
```
I0302 08:42:28.754756       1 log.go:172] FLAG: --alsologtostderr="false"
I0302 08:42:28.754805       1 log.go:172] FLAG: --burst="100"
I0302 08:42:28.754809       1 log.go:172] FLAG: --bypass-validating-webhook-xray="false"
I0302 08:42:28.754812       1 log.go:172] FLAG: --docker-registry="appscode"
I0302 08:42:28.754815       1 log.go:172] FLAG: --enable-analytics="true"
I0302 08:42:28.754819       1 log.go:172] FLAG: --help="false"
I0302 08:42:28.754822       1 log.go:172] FLAG: --image-tag="v0.9.0-rc.6"
I0302 08:42:28.754825       1 log.go:172] FLAG: --kubeconfig=""
I0302 08:42:28.754828       1 log.go:172] FLAG: --log-flush-frequency="5s"
I0302 08:42:28.754832       1 log.go:172] FLAG: --log_backtrace_at=":0"
I0302 08:42:28.754836       1 log.go:172] FLAG: --log_dir=""
I0302 08:42:28.754839       1 log.go:172] FLAG: --logtostderr="true"
I0302 08:42:28.754842       1 log.go:172] FLAG: --master=""
I0302 08:42:28.754846       1 log.go:172] FLAG: --pushgateway-url="http://stash-operator.kube-system.svc:56789"
I0302 08:42:28.754849       1 log.go:172] FLAG: --qps="100"
I0302 08:42:28.754854       1 log.go:172] FLAG: --restic-name="s3-offline"
I0302 08:42:28.754857       1 log.go:172] FLAG: --resync-period="5m0s"
I0302 08:42:28.754861       1 log.go:172] FLAG: --run-via-cron="false"
I0302 08:42:28.754864       1 log.go:172] FLAG: --scratch-dir="/tmp"
I0302 08:42:28.754867       1 log.go:172] FLAG: --service-name="stash-operator"
I0302 08:42:28.754870       1 log.go:172] FLAG: --stderrthreshold="0"
I0302 08:42:28.754874       1 log.go:172] FLAG: --use-kubeapiserver-fqdn-for-aks="true"
I0302 08:42:28.754877       1 log.go:172] FLAG: --v="3"
I0302 08:42:28.754880       1 log.go:172] FLAG: --vmodule=""
I0302 08:42:28.754884       1 log.go:172] FLAG: --workload-kind="StatefulSet"
I0302 08:42:28.754887       1 log.go:172] FLAG: --workload-name="statefulset"
W0302 08:42:28.849616       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
F0302 08:42:28.867442       1 backup.go:88] statefulsets.apps "statefulset" is forbidden: User "system:serviceaccount:mynginxproject:default" cannot get resource "statefulsets" in API group "apps" in the namespace "mynginxproject"
```

Here is my node description:
```
System Info:
  Machine ID:                 27e8a434f20d48c4a8eac14076205e34
  System UUID:                b3301be0-e8de-d740-b6f4-87c6af309026
  Boot ID:                    b8a040e7-2f7c-421d-ac98-df59e4d45b9e
  Kernel Version:             4.19.0-6-amd64
  OS Image:                   Debian GNU/Linux 10 (buster)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://18.9.7
  Kubelet Version:            v1.16.3
  Kube-Proxy Version:         v1.16.3
```

**Comment by hossainemruz** [comment] 2020-03-02 10:27
@rofra All restore for workloads (Deployment, StatefulSet, DaemonSet etc.)  are now done via init-container. That means, it is in offline mode by design. You can just follow this guide: https://stash.run/docs/v0.9.0-rc.6/guides/latest/workloads/statefulset/

**Comment by rofra** [comment] 2020-03-02 11:44
@hossainemruz : Thanks for the feedback, I don't talk about restore, I talk about offline backups.

What I found is that, due to the fact that with Offline Backups (with the Object "Restic", type: offline), the RBAC of my Statefulset is not correct with the default token because I cannot access secrets/Restics and Events. 

And due to the fact that Pods in initContainers share the same ServiceAccount that the main pod in the Statefulset. It seems I have to:
- Declare a new ServiceAccount
- Declare a new ClusterRole
- Declare a new ClusterRoleBinding
- Update my StatefulSet to use my new ServiceAccount

Am I correct ?

**Comment by hossainemruz** [comment] 2020-03-02 11:58
We highly recommend not to use the old APIs. Even, if you take backup successfully you would face problem during restore. We have fixed those problem in the new API. Try to use the new API and use Hooks to shutdown your application before backup.
Refs:
- https://stash.run/docs/v0.9.0-rc.6/guides/latest/hooks/backup-and-restore-hooks/
- https://stash.run/docs/v0.9.0-rc.6/guides/latest/hooks/configuring-hooks/

**Comment by rofra** [comment] 2020-03-02 12:15
@hossainemruz: OK, maybe you need more explanations.

I am the case of a Statefulset with a sort of Database (Custom product, not managed by your great objects). I need:
- The main pod the be stopped gracefully, wait for the stop
- The stash backup to start, _the main pod should not wake up anytime_
- One the backup is done, wake up the main pod

How can I stop the pod + make sure there won't be any concurrent access to disk from the two containers (stash is a sidecar). Any concurrent access cannot be allowed. I really don't see how to deal with the situation.

Best regards

**Comment by hossainemruz** [comment] 2020-03-02 12:28
Does your database provide any command for shutdown or any kind of read-only lock?

**Comment by rofra** [comment] 2020-03-02 12:31
@hossainemruz 
I can stop the database with a SIGTERM signal

Yes, there is a lock, in fact is is not really a read-only lock. Its a Directory Lock, once a Process locks the directory, no other process can use it. So the sidecar solution is not possible.

**Comment by rofra** [comment] 2020-03-04 11:01
FYI, I needed the following Role for RBAC to make the Resic Object working. I hope i will help someone.
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stash-initcontainer-offline
  labels:
    k8s-app: stash-initcontainer-offline
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs: ["get", "create", "update"]
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs: ["get"]
- apiGroups:
  - ""
  resources:
  - "pods/exec"
  verbs: ["get", "create"]
- apiGroups:
  - ""
  resources:
  - "replicationcontrollers"
  verbs: ["get", "list", "patch"]
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterroles"
  verbs: ["get", "create"]
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  verbs: ["get", "create"]
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups:
  - "stash.appscode.com"
  resources:
  - "repositories"
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - "stash.appscode.com"
  resources:
  - "*"
  verbs: ["*", "*"]
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - "stash.appscode.com"
  resources:
  - "restics"
  verbs:
  - "get"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "list"```

**Comment by rofra** [comment] 2020-03-04 11:02
To recap, for Offline backups (not sidecar), there is only one method (with the use of Restic in alpha1) and I should not use the alpha1 solution.

What is your proposed solution in that case ?

**Comment by hossainemruz** [comment] 2020-03-04 11:08
It's possible to write an extension for Stash to enable offline backup in the new API.

Can you please file an feature request explaining why you need offline backup and why existing backup methods are not working for your?

**Comment by rofra** [comment] 2020-03-04 11:29
Yes, done in #1065, please leave a comment if not clear

**Comment by hossainemruz** [comment] 2021-08-30 13:43
Closing in favor of #1065

**Closed by hossainemruz** 2021-08-30 13:43 UTC
Labels: feature_request
